<?xml version="1.0" encoding="utf-8"?><Database Name="BaiTapC#" Class="ThisIsLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=G3-TRUNGMI;Initial Catalog=BaiTapC#;Integrated Security=True" SettingsObjectName="DTODLL.Properties.Settings" SettingsPropertyName="BaiTapC_ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="info" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>